# Generated by Django 3.2.4 on 2021-06-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testimonial_big_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='desciption',
            new_name='description',
        ),
    ]
