# Generated by Django 3.2.4 on 2021-06-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='services',
        ),
    ]
